AGGREGATOR_DOMAINS = [
    "remotive.com", "remoteok.com", "weworkremotely.com",
    "remoteli.com",
    "upwork.com", "toptal.com", "freelancer.com", "fiverr.com",
    "workana.com", "peopleperhour.com", "progigfinder.com",
    "indeed.com", "ziprecruiter.com", "monster.com", "simplyhired.com",
    "glassdoor.com", "careerbuilder.com", "flexjobs.com",
    "dynamitejobs.com", "remoterocketship.com",
    "crossover.com", "seganrecruitment.com", "careerhound.io",
    "globalhire360.com", "jobgether.com",
    "arc.dev", "mctaba.com",
    "youtube.com", "youtu.be", "substack.com",
    "wellfound.com",
    "himalayas.app", "rubyonremote.com",
    "reddit.com", "remote.co", "nodesk.co",
    "jobviewtrack.com",
    "linkedin.com",
    "workingnomads.com", "4dayweek.io",
    "instagram.com", "facebook.com", "tiktok.com",
    "grantwriting.ca", "instrumentl.com",
    "researchbunny.com", "peopleinai.com",
    "opportunitydesk.org",
    "fundsforngos.org",
    "instantremotejobs.com",
]
