"""Entry-Level Gig & VA Platforms aggregator.

Platforms where people can find entry-level remote work: virtual assistant
tasks, data entry, customer support, transcription, content moderation,
micro-tasks, and more. These require NO college degree and are accessible
to high school graduates.

Unlike traditional job boards, these are task-based platforms — you sign
up, pass a screening test, and start getting tasks.

Platforms are curated for:
  - Legitimacy (pay reliably)
  - Remote accessibility (work from Rwanda/worldwide)
  - Low barrier to entry (no degree required)
  - Reasonable pay rates ($5-25/hr)
"""

from __future__ import annotations

from job_hunter.boards.base import Board
from job_hunter.models import Job, AUDIENCE_ENTRY


# Curated list of entry-level / VA / data entry / CX platforms.
# Updated: August 2026
PLATFORMS: list[dict] = [
    # ── Virtual Assistant Platforms ────────────────────────────────────
    {
        "name": "BELAY",
        "url": "https://www.belay.com",
        "signup": "https://www.belay.com/careers",
        "tasks": "Virtual assistant, bookkeeping, social media management",
        "pay": "$15-20/hr",
        "requirements": "US-based, 5+ years experience, background check",
        "tags": "virtual-assistant,bookkeeping,remote",
        "category": "Virtual Assistant",
    },
    {
        "name": "Time Etc",
        "url": "https://www.timeetc.com",
        "signup": "https://www.timeetc.com/for-virtual-assistants",
        "tasks": "Email management, scheduling, research, data entry",
        "pay": "$12-16/hr",
        "requirements": "English fluent, 5+ years experience",
        "tags": "virtual-assistant,data-entry,remote",
        "category": "Virtual Assistant",
    },
    {
        "name": "Zirtual",
        "url": "https://www.zirtual.com",
        "signup": "https://www.zirtual.com/virtual-assistants/",
        "tasks": "Email management, travel booking, research, social media",
        "pay": "$15-20/hr",
        "requirements": "US-based, detail-oriented",
        "tags": "virtual-assistant,admin,remote",
        "category": "Virtual Assistant",
    },
    {
        "name": "Fancy Hands",
        "url": "https://www.fancyhands.com",
        "signup": "https://www.fancyhands.com/apply",
        "tasks": "Quick tasks, scheduling, research, data lookups",
        "pay": "$3-7/task",
        "requirements": "US-based, fast turnaround",
        "tags": "microtasks,virtual-assistant,remote",
        "category": "Virtual Assistant",
    },
    # ── Data Entry & Micro-Tasks ──────────────────────────────────────
    {
        "name": "Clickworker",
        "url": "https://www.clickworker.com",
        "signup": "https://www.clickworker.com",
        "tasks": "Data entry, web research, categorization, surveys",
        "pay": "$8-15/hr",
        "requirements": "Sign up, complete profile, pass assessment",
        "tags": "data-entry,research,categorization,remote",
        "category": "Data Entry",
    },
    {
        "name": "LXT (formerly Clickworker AI)",
        "url": "https://lxt.ai",
        "signup": "https://lxt.ai",
        "tasks": "Data collection, web research, categorization, AI training",
        "pay": "$8-15/hr",
        "requirements": "Sign up, complete profile",
        "tags": "data-collection,research,remote",
        "category": "Data Entry",
    },
    {
        "name": "Amazon Mechanical Turk",
        "url": "https://www.mturk.com",
        "signup": "https://www.mturk.com/worker",
        "tasks": "Data entry, surveys, image labeling, transcription",
        "pay": "$5-12/hr (task-based)",
        "requirements": "US-based preferred, sign up + qualification tests",
        "tags": "microtasks,data-entry,transcription,remote",
        "category": "Data Entry",
    },
    {
        "name": "Appen",
        "url": "https://appen.com",
        "signup": "https://appen.com/ai-community",
        "tasks": "Data entry, search evaluation, web research, transcription",
        "pay": "$10-20/hr",
        "requirements": "Qualification test, consistent availability",
        "tags": "data-entry,evaluation,transcription,remote",
        "category": "Data Entry",
    },
    {
        "name": "Telus International (Lionbridge)",
        "url": "https://www.telusinternational.com",
        "signup": "https://www.telusinternational.com/ai-community",
        "tasks": "Data annotation, search evaluation, AI training, transcription",
        "pay": "$12-20/hr",
        "requirements": "Qualification test, consistent availability",
        "tags": "annotation,search-evaluation,transcription,remote",
        "category": "Data Entry",
    },
    # ── Customer Support / Call Center ─────────────────────────────────
    {
        "name": "ModSquad",
        "url": "https://www.modsquad.com",
        "signup": "https://join.modsquad.com/careers/",
        "tasks": "Content moderation, customer support, community management",
        "pay": "$12-18/hr",
        "requirements": "Application, interview",
        "tags": "moderation,support,community,remote",
        "category": "Customer Support",
    },
    {
        "name": "Arise",
        "url": "https://www.arise.com",
        "signup": "https://www.arise.com",
        "tasks": "Customer service, tech support, billing",
        "pay": "$10-18/hr",
        "requirements": "Background check, equipment requirements",
        "tags": "customer-support,call-center,remote",
        "category": "Customer Support",
    },
    {
        "name": "LiveWorld",
        "url": "https://www.liveworldtext.com",
        "signup": "https://apply.workable.com/liveworldtext/",
        "tasks": "Content moderation, social media support, brand monitoring",
        "pay": "$12-18/hr",
        "requirements": "Application, writing assessment",
        "tags": "moderation,social-media,remote",
        "category": "Customer Support",
    },
    # ── Transcription & Writing ───────────────────────────────────────
    {
        "name": "Rev",
        "url": "https://www.rev.com",
        "signup": "https://www.rev.com/freelancers",
        "tasks": "Audio transcription, captioning, subtitling",
        "pay": "$5-25/audio hour",
        "requirements": "Grammar test, transcription test",
        "tags": "transcription,captioning,writing,remote",
        "category": "Transcription",
    },
    {
        "name": "TranscribeMe",
        "url": "https://www.transcribeme.com",
        "signup": "https://www.transcribeme.com",
        "tasks": "Short audio transcription, medical transcription",
        "pay": "$7-22/audio hour",
        "requirements": "Entrance exam",
        "tags": "transcription,medical,remote",
        "category": "Transcription",
    },
    {
        "name": "GoTranscript",
        "url": "https://www.gotranscript.com",
        "signup": "https://www.gotranscript.com/transcription-jobs",
        "tasks": "Audio transcription, captioning",
        "pay": "$6-15/audio hour",
        "requirements": "Entrance test",
        "tags": "transcription,captioning,remote",
        "category": "Transcription",
    },
    {
        "name": "Scribie",
        "url": "https://www.scribie.com",
        "signup": "https://www.scribie.com/freelance-transcriptionist",
        "tasks": "Audio transcription, proofreading",
        "pay": "$5-20/audio hour",
        "requirements": "Entrance test",
        "tags": "transcription,proofreading,remote",
        "category": "Transcription",
    },
    # ── Content Moderation & Community ─────────────────────────────────
    {
        "name": "Teleperformance",
        "url": "https://www.teleperformance.com",
        "signup": "https://jobs.teleperformance.com",
        "tasks": "Customer support, content moderation, tech support",
        "pay": "$10-18/hr",
        "requirements": "Application, background check",
        "tags": "customer-support,moderation,remote",
        "category": "Customer Support",
    },
    {
        "name": "Foundever (Sitel Group)",
        "url": "https://www.foundever.com",
        "signup": "https://careers.foundever.com",
        "tasks": "Customer support, tech support, sales",
        "pay": "$10-16/hr",
        "requirements": "Application, assessment",
        "tags": "customer-support,sales,remote",
        "category": "Customer Support",
    },
    {
        "name": "Concentrix",
        "url": "https://www.concentrix.com",
        "signup": "https://careers.concentrix.com",
        "tasks": "Customer support, tech support, sales, billing",
        "pay": "$10-18/hr",
        "requirements": "Application, assessment",
        "tags": "customer-support,sales,remote",
        "category": "Customer Support",
    },
    # ── Freelance / Marketplace ────────────────────────────────────────
    {
        "name": "Fiverr (Seller)",
        "url": "https://www.fiverr.com",
        "signup": "https://www.fiverr.com/start_selling",
        "tasks": "Data entry, virtual assistant, writing, design, anything",
        "pay": "$5-100+/task",
        "requirements": "Create a gig, get orders",
        "tags": "freelance,data-entry,virtual-assistant,remote",
        "category": "Freelance",
    },
    {
        "name": "Upwork (Freelancer)",
        "url": "https://www.upwork.com",
        "signup": "https://www.upwork.com/nx/signup/",
        "tasks": "Data entry, virtual assistant, writing, research, admin",
        "pay": "$5-50/hr (varies widely)",
        "requirements": "Create profile, bid on jobs",
        "tags": "freelance,data-entry,virtual-assistant,remote",
        "category": "Freelance",
    },
    {
        "name": "PeoplePerHour",
        "url": "https://www.peopleperhour.com",
        "signup": "https://www.peopleperhour.com/freelancer/signup",
        "tasks": "Data entry, VA, writing, design, admin support",
        "pay": "$5-30/hr",
        "requirements": "Create profile, apply for jobs",
        "tags": "freelance,data-entry,virtual-assistant,remote",
        "category": "Freelance",
    },
    # ── More VA / Remote Assistant Platforms ───────────────────────────
    {
        "name": "Belay Solutions",
        "url": "https://belaysolutions.com",
        "signup": "https://belaysolutions.com/careers",
        "tasks": "Virtual assistant, bookkeeping, social media",
        "pay": "$18-22/hr",
        "requirements": "US-based, 7+ years experience",
        "tags": "virtual-assistant,bookkeeping,remote",
        "category": "Virtual Assistant",
    },
    {
        "name": "Boldly",
        "url": "https://www.boldly.com",
        "signup": "https://www.boldly.com/careers",
        "tasks": "Executive assistant, project management, marketing",
        "pay": "$20-30/hr",
        "requirements": "7+ years experience, English fluent",
        "tags": "executive-assistant,project-management,remote",
        "category": "Virtual Assistant",
    },
    {
        "name": "Red Buterfly (Virtual Assistant)",
        "url": "https://redbuterfly.com",
        "signup": "https://redbuterfly.com/become-a-virtual-assistant/",
        "tasks": "Admin support, email management, scheduling",
        "pay": "$10-18/hr",
        "requirements": "Apply online, interview",
        "tags": "virtual-assistant,admin,remote",
        "category": "Virtual Assistant",
    },
    # ── More Micro-Task / Data Platforms ───────────────────────────────
    {
        "name": "Hive Micro",
        "url": "https://www.hivemicro.com",
        "signup": "https://www.hivemicro.com",
        "tasks": "Image tagging, content moderation, categorization",
        "pay": "$5-15/hr (task-based)",
        "requirements": "Sign up, complete training",
        "tags": "microtasks,tagging,moderation,remote",
        "category": "Data Entry",
    },
    {
        "name": "Remotasks",
        "url": "https://www.remotasks.com",
        "signup": "https://www.remotasks.com",
        "tasks": "Data labeling, image annotation, NLP tasks",
        "pay": "$5-20/hr (task-based)",
        "requirements": "Sign up, pass training",
        "tags": "labeling,annotation,nlp,remote",
        "category": "Data Entry",
    },
    {
        "name": "Microworkers",
        "url": "https://www.microworkers.com",
        "signup": "https://www.microworkers.com",
        "tasks": "Data entry, web research, surveys, categorization",
        "pay": "$2-10/task",
        "requirements": "Sign up, no experience needed",
        "tags": "microtasks,data-entry,research,remote",
        "category": "Data Entry",
    },
    {
        "name": "Picoworkers",
        "url": "https://www.picoworkers.com",
        "signup": "https://www.picoworkers.com",
        "tasks": "Micro tasks, app downloads, sign-ups, data entry",
        "pay": "$1-5/task",
        "requirements": "Sign up, no experience needed",
        "tags": "microtasks,data-entry,remote",
        "category": "Data Entry",
    },
    {
        "name": "Clickworker (AI Tasks)",
        "url": "https://afia.clickworker.com",
        "signup": "https://afia.clickworker.com",
        "tasks": "AI training, data collection, web research",
        "pay": "$8-15/hr",
        "requirements": "Sign up, pass assessment",
        "tags": "ai-training,data-collection,research,remote",
        "category": "Data Entry",
    },
    # ── More Customer Support / CX Platforms ───────────────────────────
    {
        "name": "LiveWorld",
        "url": "https://www.liveworldtext.com",
        "signup": "https://apply.workable.com/liveworldtext/",
        "tasks": "Content moderation, social media support, brand monitoring",
        "pay": "$12-18/hr",
        "requirements": "Application, writing assessment",
        "tags": "moderation,social-media,remote",
        "category": "Customer Support",
    },
    {
        "name": "TTEC",
        "url": "https://www.ttec.com",
        "signup": "https://careers.ttec.com",
        "tasks": "Customer support, tech support, sales, billing",
        "pay": "$10-18/hr",
        "requirements": "Application, assessment",
        "tags": "customer-support,tech-support,remote",
        "category": "Customer Support",
    },
    {
        "name": "Transcom",
        "url": "https://www.transcom.com",
        "signup": "https://www.transcom.com/careers",
        "tasks": "Customer support, tech support, sales",
        "pay": "$10-16/hr",
        "requirements": "Application, assessment",
        "tags": "customer-support,sales,remote",
        "category": "Customer Support",
    },
    {
        "name": "Alorica",
        "url": "https://www.alorica.com",
        "signup": "https://www.alorica.com/careers",
        "tasks": "Customer support, tech support, billing, collections",
        "pay": "$10-16/hr",
        "requirements": "Application, assessment",
        "tags": "customer-support,billing,remote",
        "category": "Customer Support",
    },
    {
        "name": "Sutherland",
        "url": "https://www.sutherlandglobal.com",
        "signup": "https://www.sutherlandglobal.com/careers",
        "tasks": "Customer support, finance, healthcare, insurance",
        "pay": "$10-18/hr",
        "requirements": "Application, assessment",
        "tags": "customer-support,finance,remote",
        "category": "Customer Support",
    },
    {
        "name": "Arise Virtual Solutions",
        "url": "https://www.arise.com",
        "signup": "https://www.arise.com/csp",
        "tasks": "Customer service, tech support, billing, reservations",
        "pay": "$10-20/hr",
        "requirements": "Background check, home office setup",
        "tags": "customer-support,call-center,remote",
        "category": "Customer Support",
    },
    # ── More Transcription / Writing ───────────────────────────────────
    {
        "name": "CastingWords",
        "url": "https://castingwords.com",
        "signup": "https://castingwords.com/shop/transcription",
        "tasks": "Audio transcription, podcast transcription",
        "pay": "$5-15/audio hour",
        "requirements": "Entrance test",
        "tags": "transcription,podcast,remote",
        "category": "Transcription",
    },
    {
        "name": "Verbal Ink",
        "url": "https://verbalink.com",
        "signup": "https://verbalink.com/become-a-transcriptionist/",
        "tasks": "Audio transcription, legal transcription",
        "pay": "$7-20/audio hour",
        "requirements": "Entrance test, typing test",
        "tags": "transcription,legal,remote",
        "category": "Transcription",
    },
    {
        "name": "ScribeMedia",
        "url": "https://scribemedia.com",
        "signup": "https://scribemedia.com/writers",
        "tasks": "Book transcription, audio editing",
        "pay": "$10-25/audio hour",
        "requirements": "Entrance test",
        "tags": "transcription,editing,remote",
        "category": "Transcription",
    },
    # ── Search Evaluation / AI Data ────────────────────────────────────
    {
        "name": "LXT (Clickworker AI)",
        "url": "https://lxt.ai",
        "signup": "https://lxt.ai",
        "tasks": "Data collection, web research, categorization, AI training",
        "pay": "$8-15/hr",
        "requirements": "Sign up, complete profile",
        "tags": "data-collection,research,ai-training,remote",
        "category": "Data Entry",
    },
    {
        "name": "Teemwork.ai",
        "url": "https://teemwork.ai",
        "signup": "https://teemwork.ai",
        "tasks": "Data annotation, search evaluation, AI training",
        "pay": "$10-20/hr",
        "requirements": "Qualification test",
        "tags": "annotation,search-evaluation,ai-training,remote",
        "category": "Data Entry",
    },
    {
        "name": "TaskUs",
        "url": "https://www.taskus.com",
        "signup": "https://www.taskus.com/careers",
        "tasks": "Content moderation, customer support, AI training, safety",
        "pay": "$12-20/hr",
        "requirements": "Application, assessment",
        "tags": "moderation,safety,ai-training,remote",
        "category": "Customer Support",
    },
    # ── Social Media / Content Moderation ──────────────────────────────
    {
        "name": "OpenWeb",
        "url": "https://www.openweb.com",
        "signup": "https://www.openweb.com/careers",
        "tasks": "Content moderation, community management, safety",
        "pay": "$12-18/hr",
        "requirements": "Application, assessment",
        "tags": "moderation,community,safety,remote",
        "category": "Customer Support",
    },
    {
        "name": "Crisp Thinking",
        "url": "https://crispthinking.com",
        "signup": "https://crispthinking.com/careers",
        "tasks": "Content moderation, brand safety, AI training",
        "pay": "$12-18/hr",
        "requirements": "Application, assessment",
        "tags": "moderation,safety,ai-training,remote",
        "category": "Customer Support",
    },
    {
        "name": "Besedo",
        "url": "https://www.besedo.com",
        "signup": "https://www.besedo.com/careers",
        "tasks": "Content moderation, trust & safety, community management",
        "pay": "$10-16/hr",
        "requirements": "Application, assessment",
        "tags": "moderation,safety,community,remote",
        "category": "Customer Support",
    },
    # ── Freelance / Gig Platforms ──────────────────────────────────────
    {
        "name": "Freelancer.com",
        "url": "https://www.freelancer.com",
        "signup": "https://www.freelancer.com/register",
        "tasks": "Data entry, VA, writing, design, admin support",
        "pay": "$5-50/hr",
        "requirements": "Create profile, bid on jobs",
        "tags": "freelance,data-entry,virtual-assistant,remote",
        "category": "Freelance",
    },
    {
        "name": "Guru",
        "url": "https://www.guru.com",
        "signup": "https://www.guru.com/register",
        "tasks": "Data entry, VA, writing, design, admin support",
        "pay": "$5-40/hr",
        "requirements": "Create profile, bid on jobs",
        "tags": "freelance,data-entry,virtual-assistant,remote",
        "category": "Freelance",
    },
    {
        "name": "Toptal (Freelancer)",
        "url": "https://www.toptal.com",
        "signup": "https://www.toptal.com/freelancers",
        "tasks": "Writing, design, project management, finance",
        "pay": "$20-100+/hr",
        "requirements": "Rigorous screening process",
        "tags": "freelance,writing,design,remote",
        "category": "Freelance",
    },
    {
        "name": "Gengo",
        "url": "https://gengo.com",
        "signup": "https://gengo.com/translators/signup/",
        "tasks": "Translation, localization, content review",
        "pay": "$0.03-0.12/word",
        "requirements": "Language test, native proficiency",
        "tags": "translation,localization,remote",
        "category": "Transcription",
    },
    {
        "name": "One Hour Translation",
        "url": "https://www.onehourtranslation.com",
        "signup": "https://www.onehourtranslation.com/translators/apply",
        "tasks": "Translation, proofreading, transcription",
        "pay": "$0.05-0.10/word",
        "requirements": "Language test, certification preferred",
        "tags": "translation,proofreading,remote",
        "category": "Transcription",
    },
    # ── Healthcare / Medical Transcription ─────────────────────────────
    {
        "name": "Nuance Transcription",
        "url": "https://www.nuance.com",
        "signup": "https://www.nuance.com/company/careers.html",
        "tasks": "Medical transcription, documentation, coding",
        "pay": "$10-20/hr",
        "requirements": "Medical terminology knowledge preferred",
        "tags": "medical,transcription,documentation,remote",
        "category": "Transcription",
    },
    # ── Survey / Research Platforms ────────────────────────────────────
    {
        "name": "Prolific",
        "url": "https://www.prolific.co",
        "signup": "https://app.prolific.co",
        "tasks": "Research studies, surveys, AI training data",
        "pay": "$8-15/hr (minimum wage enforced)",
        "requirements": "Sign up, complete profile",
        "tags": "research,surveys,ai-training,remote",
        "category": "Data Entry",
    },
    {
        "name": "Toloka",
        "url": "https://toloka.ai",
        "signup": "https://www.toloka.ai",
        "tasks": "Image annotation, text categorization, search relevance",
        "pay": "$5-15/hr (task-based)",
        "requirements": "Sign up, complete training",
        "tags": "annotation,categorization,ai-training,remote",
        "category": "Data Entry",
    },
    {
        "name": "OneForma",
        "url": "https://www.oneforma.com",
        "signup": "https://www.oneforma.com",
        "tasks": "Data collection, transcription, AI training",
        "pay": "$10-20/hr",
        "requirements": "Qualification test",
        "tags": "data-collection,transcription,ai-training,remote",
        "category": "Data Entry",
    },
    # ── Writing / Content ──────────────────────────────────────────────
    {
        "name": "Textbroker",
        "url": "https://www.textbroker.com",
        "signup": "https://www.textbroker.com/writers/register",
        "tasks": "Content writing, blog posts, product descriptions",
        "pay": "$0.01-0.05/word",
        "requirements": "Writing sample, English test",
        "tags": "writing,content,remote",
        "category": "Creative",
    },
    {
        "name": "WriterAccess",
        "url": "https://www.writeraccess.com",
        "signup": "https://www.writeraccess.com/signup",
        "tasks": "Content writing, blog posts, social media posts",
        "pay": "$0.02-0.10/word",
        "requirements": "Portfolio, writing test",
        "tags": "writing,content,social-media,remote",
        "category": "Creative",
    },
    {
        "name": "iWriter",
        "url": "https://www.iwriter.com",
        "signup": "https://www.iwriter.com",
        "tasks": "Content writing, blog posts, articles",
        "pay": "$1-20/article",
        "requirements": "Writing test",
        "tags": "writing,content,remote",
        "category": "Creative",
    },
    {
        "name": "Constant Content",
        "url": "https://www.constant-content.com",
        "signup": "https://www.constant-content.com/write-content",
        "tasks": "Article writing, SEO content, product descriptions",
        "pay": "$5-100/article",
        "requirements": "Writing samples, editorial review",
        "tags": "writing,seo,content,remote",
        "category": "Creative",
    },
]


class EntryPlatformsBoard(Board):
    """Aggregates entry-level VA, data entry, CX, transcription platforms."""

    name = "entry_platforms"
    label = "Entry-Level Platforms (VA, Data Entry, CX, Transcription)"

    async def fetch(self, limit: int = 50) -> list[Job]:
        jobs: list[Job] = []

        for platform in PLATFORMS[:limit]:
            jobs.append(Job(
                title=f"{platform['name']} — {platform['tasks'][:60]}",
                company=platform["name"],
                url=platform["signup"],
                board=self.name,
                location="Worldwide",
                remote="Remote",
                tags=f"{platform['tags']} {platform['category']}",
                description=(
                    f"Platform: {platform['name']}\\n"
                    f"Category: {platform['category']}\\n"
                    f"Tasks: {platform['tasks']}\\n"
                    f"Pay: {platform['pay']}\\n"
                    f"Requirements: {platform['requirements']}\\n"
                    f"Website: {platform['url']}"
                ),
                posted_at="",
                eligible_countries=[],
                audience=AUDIENCE_ENTRY,
            ))

        return jobs
